camera_intrinsic_parameters: [745, 0, 640, 0, 745, 360, 0, 0, 1]

# seguimiento: [97, 99]
seguimiento: [96, 97, 98, 99]

# Translation gains
gain_v_ini: 0.5
gain_v_max: 1.0
l_prime_v: 0.1

# Rotation gains
gain_w_ini: 0.2
gain_w_max: 0.8
l_prime_w: 1.0

# Saturation values from (-max_vel, max_vel)
max_vel: 0.3

# -> Leader             |  -> Follower
#     1: 1/dist,        |       1: -P_gij * gij*
#     2: dist           |       2: gij - gij*
control: 1

# Send velocities
# 0: move_relative
# 1: fly_direct
vels: 0
