camera_intrinsic_parameters: [745,   0,    640,
                              0,    745,   360,
                              0,     0,     1]

seguimiento: [96, 99]

gain_v: 1
gain_v_max: 1

gain_w: 1
gain_w_max: 1

# 1: 1/dist, 2: dist
control: 1 