camera_intrinsic_parameters: [750,   0,    640,
                              0,    750,   360,
                              0,     0,     1]

seguimiento: [99]

bearings: []

gain_v: 1
gain_v_max: 1

gain_w: 1
gain_w_max: 1

# 1: 1/dist, 2: dist
control: 1 